# Generated by Django 5.0.4 on 2024-04-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_avertising_alter_t_shirts_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_shirts',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_shirts',
            name='price_type',
            field=models.CharField(choices=[("so'm", "so'm"), ('$', '$'), ('₽', '₽')], default="so'm", max_length=10),
        ),
    ]
