# Generated by Django 5.0.4 on 2024-04-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_t_shirts_last_name_alter_t_shirts_price_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='t_shirts',
            name='price_type',
            field=models.CharField(choices=[("so'm", "so'm"), ('₽', '₽'), ('$', '$')], default="so'm", max_length=10),
        ),
    ]
