# Generated by Django 5.0.4 on 2024-04-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_register_alter_t_shirts_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_shirts',
            name='price_type',
            field=models.CharField(choices=[('$', '$'), ("so'm", "so'm"), ('₽', '₽')], default="so'm", max_length=10),
        ),
    ]
